name: Buyme product CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  GKE_CLUSTER: buyme-product-cluster    # TODO: update to cluster name
  GKE_ZONE: asia-southeast1   # TODO: update to cluster zone

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: chalaka78/product_image:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Push to Google cloud
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_SERVICE_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f k8s/
